# 1.Data Understanding

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Import the required library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [3]:
# read dataset
missing_val = ['?']
df = pd.read_csv("adult.csv",na_values=missing_val)

In [4]:
# Display the top five rows of dataset
df.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18        NaN  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                NaN    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [5]:
# display the bottom five rows of dataset
df.tail()

age     workclass  fnlwgt   education  educational-num  \
48837   27       Private  257302  Assoc-acdm               12   
48838   40       Private  154374     HS-grad                9   
48839   58       Private  151910     HS-grad                9   
48840   22       Private  201490     HS-grad                9   
48841   52  Self-emp-inc  287927     HS-grad                9   

           marital-status         occupation relationship   race  gender  \
48837  Married-civ-spouse       Tech-support         Wife  White  Female   
48838  Married-civ-spouse  Machine-op-inspct      Husband  White    Male   
48839             Widowed       Adm-clerical    Unmarried  White  Female   
48840       Never-married       Adm-clerical    Own-child  White    Male   
48841  Married-civ-spouse    Exec-managerial         Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country income  
48837             0             0              38  United-States  <=50K  
48838             0             0              40  United-States   >50K  
48839             0             0              40  United-States  <=50K  
48840             0             0              20  United-States  <=50K  
48841         15024             0              40  United-States   >50K

In [6]:
df.columns


Index(['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [7]:
# display the statistical analysis of numerical column
df.describe()

age        fnlwgt  educational-num  capital-gain  \
count  48842.000000  4.884200e+04     48842.000000  48842.000000   
mean      38.643585  1.896641e+05        10.078089   1079.067626   
std       13.710510  1.056040e+05         2.570973   7452.019058   
min       17.000000  1.228500e+04         1.000000      0.000000   
25%       28.000000  1.175505e+05         9.000000      0.000000   
50%       37.000000  1.781445e+05        10.000000      0.000000   
75%       48.000000  2.376420e+05        12.000000      0.000000   
max       90.000000  1.490400e+06        16.000000  99999.000000   

       capital-loss  hours-per-week  
count  48842.000000    48842.000000  
mean      87.502314       40.422382  
std      403.004552       12.391444  
min        0.000000        1.000000  
25%        0.000000       40.000000  
50%        0.000000       40.000000  
75%        0.000000       45.000000  
max     4356.000000       99.000000

In [8]:
# how many rows and columns there in dataset
df.shape

(48842, 15)

In [9]:
print(df.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              48842 non-null  int64 
 1   workclass        46043 non-null  object
 2   fnlwgt           48842 non-null  int64 
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64 
 5   marital-status   48842 non-null  object
 6   occupation       46033 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64 
 11  capital-loss     48842 non-null  int64 
 12  hours-per-week   48842 non-null  int64 
 13  native-country   47985 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB
None


In [10]:
total_rows = len(df)
del_row = df.isnull().any(axis = 1).sum()
print(total_rows, del_row)

48842 3620


In [11]:
# rows with atleast one missing value
df.isnull().any(axis=1)

0        False
1        False
2        False
3        False
4         True
         ...  
48837    False
48838    False
48839    False
48840    False
48841    False
Length: 48842, dtype: bool

In [12]:
# remove all the missing values by removing the rows where missing value occur
df.dropna(axis = 0, how = 'any' , inplace=True)
df.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
5   34    Private  198693          10th                6       Never-married   

          occupation   relationship   race gender  capital-gain  capital-loss  \
0  Machine-op-inspct      Own-child  Black   Male             0             0   
1    Farming-fishing        Husband  White   Male             0             0   
2    Protective-serv        Husband  White   Male             0             0   
3  Machine-op-inspct        Husband  Black   Male          7688             0   
5      Other-service  Not-in-family  White   Male             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
5              30  United-States  <=50K

In [13]:
current_rows = len(df)
print(current_rows)

45222


# 2. Data Preparation

* Consider 'income' as the target variable 

* Remove unnecessary columns (for eg 'fnlwgt')

* standardizing numerical data

* Encoding categorical features 

* Train Test Split

In [14]:
# remove fnlwgt column 
df.drop(['fnlwgt'] , axis=1, inplace=True)
df.head()

age  workclass     education  educational-num      marital-status  \
0   25    Private          11th                7       Never-married   
1   38    Private       HS-grad                9  Married-civ-spouse   
2   28  Local-gov    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  Some-college               10  Married-civ-spouse   
5   34    Private          10th                6       Never-married   

          occupation   relationship   race gender  capital-gain  capital-loss  \
0  Machine-op-inspct      Own-child  Black   Male             0             0   
1    Farming-fishing        Husband  White   Male             0             0   
2    Protective-serv        Husband  White   Male             0             0   
3  Machine-op-inspct        Husband  Black   Male          7688             0   
5      Other-service  Not-in-family  White   Male             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
5              30  United-States  <=50K

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45222 entries, 0 to 48841
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              45222 non-null  int64 
 1   workclass        45222 non-null  object
 2   education        45222 non-null  object
 3   educational-num  45222 non-null  int64 
 4   marital-status   45222 non-null  object
 5   occupation       45222 non-null  object
 6   relationship     45222 non-null  object
 7   race             45222 non-null  object
 8   gender           45222 non-null  object
 9   capital-gain     45222 non-null  int64 
 10  capital-loss     45222 non-null  int64 
 11  hours-per-week   45222 non-null  int64 
 12  native-country   45222 non-null  object
 13  income           45222 non-null  object
dtypes: int64(5), object(9)
memory usage: 5.2+ MB


In [16]:
# separating target and input variable
target=df['income']
inputs=df.drop('income',axis=1)

In [17]:
categorical = inputs.select_dtypes(include =['object'])
categorical.head()

workclass     education      marital-status         occupation  \
0    Private          11th       Never-married  Machine-op-inspct   
1    Private       HS-grad  Married-civ-spouse    Farming-fishing   
2  Local-gov    Assoc-acdm  Married-civ-spouse    Protective-serv   
3    Private  Some-college  Married-civ-spouse  Machine-op-inspct   
5    Private          10th       Never-married      Other-service   

    relationship   race gender native-country  
0      Own-child  Black   Male  United-States  
1        Husband  White   Male  United-States  
2        Husband  White   Male  United-States  
3        Husband  Black   Male  United-States  
5  Not-in-family  White   Male  United-States

In [18]:
numerical = inputs.select_dtypes(include =['int64','float64'])
numerical.head()

age  educational-num  capital-gain  capital-loss  hours-per-week
0   25                7             0             0              40
1   38                9             0             0              50
2   28               12             0             0              40
3   44               10          7688             0              40
5   34                6             0             0              30

In [19]:
# scaling the numerical features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

#column names are (annoyingly) lost after scaling
#(i.e. the dataframe is converted to a numpy ndarray)

df_num = pd.DataFrame(scaler.fit_transform(numerical),columns=numerical.columns)

df_num.head()

age  educational-num  capital-gain  capital-loss  hours-per-week
0 -1.024983        -1.221559     -0.146733      -0.21878       -0.078120
1 -0.041455        -0.438122     -0.146733      -0.21878        0.754701
2 -0.798015         0.737034     -0.146733      -0.21878       -0.078120
3  0.412481        -0.046403      0.877467      -0.21878       -0.078120
4 -0.344079        -1.613277     -0.146733      -0.21878       -0.910942

In [20]:
# Encoding the categorical features

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(drop='first', sparse=False)

# column names are (annoyingly) lost after OneHotEncoding
# (i.e. the dataframe is converted to a numpy ndarray)

df_cat = pd.DataFrame(encoder.fit_transform(categorical), 
                      columns=encoder.get_feature_names(categorical.columns))

df_cat.head()


workclass_Local-gov  workclass_Private  workclass_Self-emp-inc  \
0                  0.0                1.0                     0.0   
1                  0.0                1.0                     0.0   
2                  1.0                0.0                     0.0   
3                  0.0                1.0                     0.0   
4                  0.0                1.0                     0.0   

   workclass_Self-emp-not-inc  workclass_State-gov  workclass_Without-pay  \
0                         0.0                  0.0                    0.0   
1                         0.0                  0.0                    0.0   
2                         0.0                  0.0                    0.0   
3                         0.0                  0.0                    0.0   
4                         0.0                  0.0                    0.0   

   education_11th  education_12th  education_1st-4th  education_5th-6th  ...  \
0             1.0             0.0                0.0                0.0  ...   
1             0.0             0.0                0.0                0.0  ...   
2             0.0             0.0                0.0                0.0  ...   
3             0.0             0.0                0.0                0.0  ...   
4             0.0             0.0                0.0                0.0  ...   

   native-country_Portugal  native-country_Puerto-Rico  \
0                      0.0                         0.0   
1                      0.0                         0.0   
2                      0.0                         0.0   
3                      0.0                         0.0   
4                      0.0                         0.0   

   native-country_Scotland  native-country_South  native-country_Taiwan  \
0                      0.0                   0.0                    0.0   
1                      0.0                   0.0                    0.0   
2                      0.0                   0.0                    0.0   
3                      0.0                   0.0                    0.0   
4                      0.0                   0.0                    0.0   

   native-country_Thailand  native-country_Trinadad&Tobago  \
0                      0.0                             0.0   
1                      0.0                             0.0   
2                      0.0                             0.0   
3                      0.0                             0.0   
4                      0.0                             0.0   

   native-country_United-States  native-country_Vietnam  \
0                           1.0                     0.0   
1                           1.0                     0.0   
2                           1.0                     0.0   
3                           1.0                     0.0   
4                           1.0                     0.0   

   native-country_Yugoslavia  
0                        0.0  
1                        0.0  
2                        0.0  
3                        0.0  
4                        0.0  

[5 rows x 90 columns]

In [21]:
df = pd.concat([df_num, df_cat], axis=1)
df.head()


age  educational-num  capital-gain  capital-loss  hours-per-week  \
0 -1.024983        -1.221559     -0.146733      -0.21878       -0.078120   
1 -0.041455        -0.438122     -0.146733      -0.21878        0.754701   
2 -0.798015         0.737034     -0.146733      -0.21878       -0.078120   
3  0.412481        -0.046403      0.877467      -0.21878       -0.078120   
4 -0.344079        -1.613277     -0.146733      -0.21878       -0.910942   

   workclass_Local-gov  workclass_Private  workclass_Self-emp-inc  \
0                  0.0                1.0                     0.0   
1                  0.0                1.0                     0.0   
2                  1.0                0.0                     0.0   
3                  0.0                1.0                     0.0   
4                  0.0                1.0                     0.0   

   workclass_Self-emp-not-inc  workclass_State-gov  ...  \
0                         0.0                  0.0  ...   
1                         0.0                  0.0  ...   
2                         0.0                  0.0  ...   
3                         0.0                  0.0  ...   
4                         0.0                  0.0  ...   

   native-country_Portugal  native-country_Puerto-Rico  \
0                      0.0                         0.0   
1                      0.0                         0.0   
2                      0.0                         0.0   
3                      0.0                         0.0   
4                      0.0                         0.0   

   native-country_Scotland  native-country_South  native-country_Taiwan  \
0                      0.0                   0.0                    0.0   
1                      0.0                   0.0                    0.0   
2                      0.0                   0.0                    0.0   
3                      0.0                   0.0                    0.0   
4                      0.0                   0.0                    0.0   

   native-country_Thailand  native-country_Trinadad&Tobago  \
0                      0.0                             0.0   
1                      0.0                             0.0   
2                      0.0                             0.0   
3                      0.0                             0.0   
4                      0.0                             0.0   

   native-country_United-States  native-country_Vietnam  \
0                           1.0                     0.0   
1                           1.0                     0.0   
2                           1.0                     0.0   
3                           1.0                     0.0   
4                           1.0                     0.0   

   native-country_Yugoslavia  
0                        0.0  
1                        0.0  
2                        0.0  
3                        0.0  
4                        0.0  

[5 rows x 95 columns]

In [22]:
# split into train and test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df,\
                                                   target,\
                                                   test_size=0.25,\
                                                   random_state=0)


In [23]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)


(33916, 95) (33916,)
(11306, 95) (11306,)


# 3.Train the model on Training Data

In [24]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

# 4. Prediction

In [25]:
y_pred = classifier.predict(X_test)


# 5.Evaluation

In [26]:
# calculate accuracy of class predictions
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred)


0.8394657703874049

In [27]:
# print the confusion matrix
con_metrics = metrics.confusion_matrix(y_test, y_pred)
con_metrics


array([[7810,  657],
       [1158, 1681]], dtype=int64)

In [28]:
#Checking Precision, Recall and F1 Score
print(metrics.classification_report(y_test, y_pred))


              precision    recall  f1-score   support

       <=50K       0.87      0.92      0.90      8467
        >50K       0.72      0.59      0.65      2839

    accuracy                           0.84     11306
   macro avg       0.79      0.76      0.77     11306
weighted avg       0.83      0.84      0.83     11306



# 6.Recursive  Feature Elimination

In [29]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression



In [30]:
model= LogisticRegression(solver='lbfgs')



In [31]:
rfe=RFE(model,3)


In [32]:
fit=rfe.fit(X_train,y_train)

In [33]:
print(rfe.support_)
print(rfe.ranking_)

[False False  True False False False False False False False False False
 False False False False False False False False False False False False
 False False False  True False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False  True False False False False
 False False False False False False False False False False False]
[33 14  1 57 35 53 54 55 31 38 16 64 93 11 10 85 91 58 73 81 78 74 80 32
 27 82 12  1 61 39 76 79 59 75 25  8  7 28  4  2 37 52 62 36 83 65  9  3
 66 23 42 44 45 43 24 29 56  6 60 20 15 22 46 30 51 68 17 87 90 71 63 89
 72 84 26 47 49 70 86  1 92 67 19 50 69 40 77 18 13 88 34 21 48  5 41]


In [34]:
imp_col = X_train.columns[rfe.support_]
imp_col

Index(['capital-gain', 'marital-status_Married-civ-spouse',
       'native-country_Mexico'],
      dtype='object')

In [35]:
X_train_new = X_train[imp_col]

X_train_new.head()

capital-gain  marital-status_Married-civ-spouse  native-country_Mexico
36418     -0.146733                                0.0                    0.0
1080      -0.146733                                0.0                    0.0
17957     -0.146733                                1.0                    0.0
13607     -0.146733                                1.0                    0.0
43125     -0.146733                                0.0                    0.0

In [36]:
from sklearn.linear_model import LogisticRegression
regressor_new = LogisticRegression()
regressor_new.fit(X_train_new, y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [37]:
X_test_new = X_test[imp_col]

y_test_pred_new = regressor_new.predict(X_test_new)


In [38]:
temp_df_new = pd.DataFrame({'Actual': y_test, 'Predicted': y_test_pred_new})
temp_df_new


Actual Predicted
44688  <=50K     <=50K
38106  <=50K     <=50K
29131  <=50K     <=50K
31472   >50K     <=50K
45120  <=50K     <=50K
...      ...       ...
1915    >50K     <=50K
24393  <=50K     <=50K
31714  <=50K     <=50K
34235  <=50K     <=50K
10770  <=50K     <=50K

[11306 rows x 2 columns]

In [39]:
# evaluation
from sklearn import metrics
metrics.accuracy_score(y_test, y_test_pred_new)



0.7802936493897046

# 7.Principal Component Analysis

In [40]:
from sklearn.decomposition import PCA
pca = PCA(random_state = 0)


In [41]:
pca.fit(X_train)


PCA(copy=True, iterated_power='auto', n_components=None, random_state=0,
    svd_solver='auto', tol=0.0, whiten=False)

In [42]:
pca.explained_variance_ratio_


array([1.72884066e-01, 1.27421944e-01, 1.19771952e-01, 1.03923969e-01,
       9.88034227e-02, 4.64266383e-02, 2.97047265e-02, 2.59673865e-02,
       2.57811010e-02, 2.07823322e-02, 1.86364403e-02, 1.77758038e-02,
       1.53792156e-02, 1.40253990e-02, 1.33726860e-02, 1.14520237e-02,
       1.06357552e-02, 1.03917445e-02, 9.36003151e-03, 8.40142713e-03,
       7.45111599e-03, 7.26331300e-03, 6.48811999e-03, 5.94015043e-03,
       5.45434778e-03, 4.95469118e-03, 4.36740887e-03, 4.09068718e-03,
       4.03837163e-03, 3.94145179e-03, 3.83638920e-03, 3.47166038e-03,
       3.38172277e-03, 3.35506898e-03, 2.99719033e-03, 2.33475156e-03,
       2.32617035e-03, 2.16725076e-03, 1.90163324e-03, 1.66420391e-03,
       1.59605521e-03, 1.51824831e-03, 1.24896923e-03, 1.22611941e-03,
       1.11282847e-03, 9.93757072e-04, 7.04947588e-04, 6.32020345e-04,
       5.99101331e-04, 5.37684285e-04, 4.82647760e-04, 4.42630451e-04,
       4.03620754e-04, 3.52324748e-04, 3.43363791e-04, 3.24168572e-04,
      

In [43]:
from sklearn.decomposition import PCA

pca_final = PCA(n_components = 15, random_state = 0)

X_train_pca = pca_final.fit_transform(X_train)


In [44]:
X_train_pca.shape

(33916, 15)

In [45]:
X_test_pca = pca_final.transform(X_test)




## 1. Using LogisticRegression

In [46]:
# Building the final model 

from sklearn.linear_model import LogisticRegression

regressor_pca = LogisticRegression()

regressor_pca.fit(X_train_pca, y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [47]:
# print coefficients and intercept

print(regressor_pca.coef_)

print(regressor_pca.intercept_)


[[ 2.41620602  0.67299729  1.22626226  0.68676783  0.66316862 -1.32511814
  -0.02732083 -0.0104878  -0.55757335 -0.23138172  0.64960024 -0.79357992
   0.42443382  0.11592181 -0.457153  ]]
[-1.8272882]


In [48]:
# split into train and test
from sklearn.model_selection import train_test_split

X_train_pca, X_test_pca, y_train, y_test = train_test_split(df,\
                                                   target,\
                                                   test_size=0.25,\
                                                   random_state=0)


In [49]:
y_pred = classifier.predict(X_test)


In [50]:
 #evaluation
from sklearn.metrics import  confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))


[[7810  657]
 [1158 1681]]
0.8394657703874049


In [51]:
#classification report
print(metrics.classification_report(y_test, y_pred))


              precision    recall  f1-score   support

       <=50K       0.87      0.92      0.90      8467
        >50K       0.72      0.59      0.65      2839

    accuracy                           0.84     11306
   macro avg       0.79      0.76      0.77     11306
weighted avg       0.83      0.84      0.83     11306



## 2. Using KNN

In [52]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(X_train, y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [53]:
y_pred = classifier.predict(X_test)


In [54]:
 #evaluation
from sklearn.metrics import  confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))


[[7611  856]
 [1082 1757]]
0.8285865911905184


In [55]:
#classification report
print(metrics.classification_report(y_test, y_pred))


              precision    recall  f1-score   support

       <=50K       0.88      0.90      0.89      8467
        >50K       0.67      0.62      0.64      2839

    accuracy                           0.83     11306
   macro avg       0.77      0.76      0.77     11306
weighted avg       0.82      0.83      0.83     11306



## 3. Using DecisionTree

In [56]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(max_depth = 2)
classifier.fit(X_train, y_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=2, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [57]:
y_pred = classifier.predict(X_test)


In [58]:
 #evaluation
from sklearn.metrics import  confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))


[[7911  556]
 [1494 1345]]
0.8186803467185565


In [59]:
#Classification report
print(metrics.classification_report(y_test, y_pred))


              precision    recall  f1-score   support

       <=50K       0.84      0.93      0.89      8467
        >50K       0.71      0.47      0.57      2839

    accuracy                           0.82     11306
   macro avg       0.77      0.70      0.73     11306
weighted avg       0.81      0.82      0.81     11306



## 4.Support Vecor Machine

In [60]:
from sklearn.svm import SVC
classifier = SVC()
classifier.fit(X_train, y_train)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [64]:
y_pred = classifier.predict(X_test)


In [62]:
 #evaluation
from sklearn.metrics import  confusion_matrix
from sklearn.metrics import accuracy_score

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))


[[7912  555]
 [1184 1655]]
0.8461878648505219


In [65]:
#Classification report
print(metrics.classification_report(y_test, y_pred))


              precision    recall  f1-score   support

       <=50K       0.87      0.93      0.90      8467
        >50K       0.75      0.58      0.66      2839

    accuracy                           0.85     11306
   macro avg       0.81      0.76      0.78     11306
weighted avg       0.84      0.85      0.84     11306

